### ISSUE TITLE
[Task] CLI should be more verbose on errors, e.g. folder structure

### ISSUE THREAD

**Issue by matgnt** [eclipse-esmf/esmf-sdk#353]
```
$ java -jar bamm-cli-2.1.0.jar aspect com.ids.protocol/0.8/ContractOfferMessageShape.ttl to openapi --api-base-url=http://localhost
io.openmanufacturing.sds.exception.CommandException: The URN constructed from the input file path is invalid: urn:bamm:com.ids.protocol:0.8#ContractOfferMessageShape
        at io.openmanufacturing.sds.AbstractCommand.lambda$fileToUrn$4(AbstractCommand.java:97)
        at io.vavr.Value.getOrElse(Value.java:380)
        at io.openmanufacturing.sds.AbstractCommand.fileToUrn(AbstractCommand.java:96)
        at io.openmanufacturing.sds.AbstractCommand.loadAndResolveModel(AbstractCommand.java:58)
        at io.openmanufacturing.sds.AbstractCommand.loadAndResolveModel(AbstractCommand.java:65)
        at io.openmanufacturing.sds.AbstractCommand.loadModelOrFail(AbstractCommand.java:114)
        at io.openmanufacturing.sds.aspect.to.AspectToOpenapiCommand.run(AspectToOpenapiCommand.java:108)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at io.openmanufacturing.sds.BammCli.main(BammCli.java:64)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
```

It turned out after comparing with working *.ttls that my directory name `0.8` was not accepted and should be `0.8.0` instead. It might also be useful to pass in the URN as a input parameter.

---
Matthias Binzer

**Comment by atextor** [comment]
Related: #354
