### ISSUE TITLE
[BUG] Sporadically TurtleLoader.loadTurtle fails

### ISSUE THREAD

**Issue by external-Bogdan-Toma** [eclipse-esmf/esmf-sdk#411]
**Describe the bug**
Using TurtleLoader.loadTurtle fails sometime in a multi threading setup due to registering TURTLE language and this is not a thread safe operation. This can occur not only when loading a custom ttl, but also when loading meta-model files (e.g calling SammAspectMetaModelResourceResolver.mergeMetaModelIntoRawModel)
``` 
RDFParserRegistry.registerLangTriples( Lang.TURTLE, ReaderRIOTTurtle.factory );
```
java.lang.IllegalStateException: Expect to find '[text/turtle]'. The full stacktrace is attached at end.

**Where**
esmf-aspect-meta-model-resolver:2.3.1

**Additional context**
- The test proves the problem (maybe there is a need to change number of threads)
[org.example.turtleloader.zip](https://github.com/eclipse-esmf/esmf-sdk/files/12319192/org.example.turtleloader.zip)
- Stacktrace:
java.lang.IllegalStateException: Expect to find '[text/turtle]'
	at org.apache.jena.riot.RDFLanguages.register(RDFLanguages.java:280)
	at org.apache.jena.riot.RDFParserRegistry.registerLang(RDFParserRegistry.java:130)
	at org.apache.jena.riot.RDFParserRegistry.registerLangTriples(RDFParserRegistry.java:140)
	at org.eclipse.esmf.aspectmodel.resolver.services.TurtleLoader.loadTurtle(TurtleLoader.java:65)
	at example.TurtleLoaderTest.lambda$turtleLoaderTest$0(TurtleLoaderTest.java:23)
	at java.base/java.lang.Thread.run(Thread.java:833)
- Idea: implement maybe something similar to org.eclipse.esmf.aspectmodel.resolver.services.DataType.setupTypeMapping

**Comment by soriniov** [comment]
@chris-volk , @atextor, is there any update regarding this issue?
