### ISSUE TITLE
Unable to open .aasx file which is created by using SAMM CLI 

### ISSUE THREAD

**Issue by Punith-Arumilli** [eclipse-esmf/esmf-sdk#496]
Hi,
I created Aspect Model and I converted it into Asset Administration Shell using SAMM CLI. Now if I am trying to open it using AASX Package Explorer it is showing an error.

Loading aasx file repository ..........\Sample_AAS\aasxrepo-new.json ..
File not found when loading aasx file repository ..........\Sample_AAS\aasxrepo-new.json
Application started ..
[AasxPluginAdvancedTextEditor] ListActions() called
[AasxPluginAdvancedTextEditor] InitPlugin() called with args =
[AasxPluginBomStructure] ListActions() called
[AasxPluginBomStructure] InitPlugin() called with args =
[AasxPluginDocumentShelf] InitPlugin() called with args =
[AasxPluginExportTable] ListActions() called
[AasxPluginExportTable] InitPlugin() called with args =
[AasxPluginGenericForms] ListActions() called
[AasxPluginGenericForms] InitPlugin() called with args =
[AasxPluginImageMap] ListActions() called
[AasxPluginImageMap] InitPlugin() called with args =
[AasxPluginMtpViewer] GetPluginName() = MtpViewer
[AasxPluginMtpViewer] ListActions() called
[AasxPluginMtpViewer] InitPlugin() called with args =
[AasxPluginMtpViewer] GetPluginName() = MtpViewer
[AasxPluginPlotting] ListActions() called
[AasxPluginPlotting] InitPlugin() called with args =
[AasxPluginSmdExporter] ListActions() called
[AasxPluginSmdExporter] InitPlugin() called with args =
[AasxPluginTechnicalData] ListActions() called
[AasxPluginTechnicalData] InitPlugin() called with args =
[AasxPluginOpcUaClient] ListActions() called
[AasxPluginUaNetServer] GetPluginName() = Net46AasxServerPlugin
[AasxPluginUaNetServer] ListActions() called
[AasxPluginUaNetServer] InitPlugin() called with args =
[AasxPluginUaNetServer] GetPluginName() = Net46AasxServerPlugin
[AasxPluginWebBrowser] ListActions() called
[AasxPluginWebBrowser] InitPlugin() called with args =
Loading new AASX from: C:\Users\punit\Downloads\MeasurementUnit.aasx as auxiliary False ..
Error: Unhandled exception in AasxPackageExplorer v1.0.0.0: PackageCentral: while performing load from C:\Users\punit\Downloads\MeasurementUnit.aasx at \PackageCentral.cs:line 95 gave: One or more errors occurred. PackageCentral: while performing load from C:\Users\punit\Downloads\MeasurementUnit.aasx at \PackageCentral.cs:line 95 gave: One or more errors occurred.
InnerException: One or more errors occurred.
InnerException: While opening aasx C:\Users\punit\AppData\Local\Temp\tmp905C.aasx from source local file: C:\Users\punit\Downloads\MeasurementUnit.aasx buffered to: C:\Users\punit\AppData\Local\Temp\tmp905C.aasx at \AdminShellPackageEnv.cs:line 402 gave: While reading the AASX C:\Users\punit\AppData\Local\Temp\tmp905C.aasx at \AdminShellPackageEnv.cs:line 313 gave: Part URI must start with a forward slash. at at AasxPackageLogic.PackageCentral.PackageCentralItem.Load(PackageCentral packageCentral, String location, String fullItemLocation, Boolean overrideLoadResident, PackageContainerOptionsBase containerOptions, PackCntRuntimeOptions runtimeOptions) in D:\a\aasx-package-explorer\aasx-package-explorer\src\AasxPackageLogic\PackageCentral\PackageCentral.cs:line 104
at AasxPackageExplorer.MainWindow.UiLoadPackageWithNew(PackageCentralItem packItem, AdminShellPackageEnv takeOverEnv, String loadLocalFilename, String info, Boolean onlyAuxiliary, Boolean doNotNavigateAfterLoaded, PackageContainerBase takeOverContainer, String storeFnToLRU, Boolean indexItems) in D:\a\aasx-package-explorer\aasx-package-explorer\src\AasxPackageExplorer\MainWindow.xaml.cs:line 294
at AasxPackageExplorer.MainWindow.<CommandBinding_GeneralDispatch>d__5.MoveNext() in D:\a\aasx-package-explorer\aasx-package-explorer\src\AasxPackageExplorer\MainWindow.CommandBindings.cs:line 266
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler).
Stacktrace: at AasxPackageLogic.PackageCentral.PackageCentralItem.Load(PackageCentral packageCentral, String location, String fullItemLocation, Boolean overrideLoadResident, PackageContainerOptionsBase containerOptions, PackCntRuntimeOptions runtimeOptions) in D:\a\aasx-package-explorer\aasx-package-explorer\src\AasxPackageLogic\PackageCentral\PackageCentral.cs:line 104
at AasxPackageExplorer.MainWindow.UiLoadPackageWithNew(PackageCentralItem packItem, AdminShellPackageEnv takeOverEnv, String loadLocalFilename, String info, Boolean onlyAuxiliary, Boolean doNotNavigateAfterLoaded, PackageContainerBase takeOverContainer, String storeFnToLRU, Boolean indexItems) in D:\a\aasx-package-explorer\aasx-package-explorer\src\AasxPackageExplorer\MainWindow.xaml.cs:line 294
at AasxPackageExplorer.MainWindow.<CommandBinding_GeneralDispatch>d__5.MoveNext() in D:\a\aasx-package-explorer\aasx-package-explorer\src\AasxPackageExplorer\MainWindow.CommandBindings.cs:line 266
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
Loading new AASX from: C:\Users\punit\Downloads\Universal_Robot.aasx as auxiliary False ..
AASX C:\Users\punit\Downloads\Universal_Robot.aasx loaded.
[AasxPluginExportTable] Export UML data to file: C:\Users\punit\Desktop\new.uml
[AasxPluginExportTable] Export UML data copied to paste buffer.
[AasxPluginExportTable] Export UML data to file: C:\Users\punit\Downloads\new.xml
[AasxPluginExportTable] Export UML data copied to paste buffer.
[AasxPluginExportTable] Exporting table: C:\Users\punit\Downloads\new.docx
Loading new AASX from: C:\Users\punit\Downloads\MeasurementUnit.aasx as auxiliary False ..
Error: Unhandled exception in AasxPackageExplorer v1.0.0.0: PackageCentral: while performing load from C:\Users\punit\Downloads\MeasurementUnit.aasx at \PackageCentral.cs:line 95 gave: One or more errors occurred. PackageCentral: while performing load from C:\Users\punit\Downloads\MeasurementUnit.aasx at \PackageCentral.cs:line 95 gave: One or more errors occurred.
InnerException: One or more errors occurred.
InnerException: While opening aasx C:\Users\punit\AppData\Local\Temp\tmp475F.aasx from source local file: C:\Users\punit\Downloads\MeasurementUnit.aasx buffered to: C:\Users\punit\AppData\Local\Temp\tmp475F.aasx at \AdminShellPackageEnv.cs:line 402 gave: While reading the AASX C:\Users\punit\AppData\Local\Temp\tmp475F.aasx at \AdminShellPackageEnv.cs:line 313 gave: Part URI must start with a forward slash. at at AasxPackageLogic.PackageCentral.PackageCentralItem.Load(PackageCentral packageCentral, String location, String fullItemLocation, Boolean overrideLoadResident, PackageContainerOptionsBase containerOptions, PackCntRuntimeOptions runtimeOptions) in D:\a\aasx-package-explorer\aasx-package-explorer\src\AasxPackageLogic\PackageCentral\PackageCentral.cs:line 104
at AasxPackageExplorer.MainWindow.UiLoadPackageWithNew(PackageCentralItem packItem, AdminShellPackageEnv takeOverEnv, String loadLocalFilename, String info, Boolean onlyAuxiliary, Boolean doNotNavigateAfterLoaded, PackageContainerBase takeOverContainer, String storeFnToLRU, Boolean indexItems) in D:\a\aasx-package-explorer\aasx-package-explorer\src\AasxPackageExplorer\MainWindow.xaml.cs:line 294
at AasxPackageExplorer.MainWindow.<CommandBinding_GeneralDispatch>d__5.MoveNext() in D:\a\aasx-package-explorer\aasx-package-explorer\src\AasxPackageExplorer\MainWindow.CommandBindings.cs:line 266
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler).
Stacktrace: at AasxPackageLogic.PackageCentral.PackageCentralItem.Load(PackageCentral packageCentral, String location, String fullItemLocation, Boolean overrideLoadResident, PackageContainerOptionsBase containerOptions, PackCntRuntimeOptions runtimeOptions) in D:\a\aasx-package-explorer\aasx-package-explorer\src\AasxPackageLogic\PackageCentral\PackageCentral.cs:line 104
at AasxPackageExplorer.MainWindow.UiLoadPackageWithNew(PackageCentralItem packItem, AdminShellPackageEnv takeOverEnv, String loadLocalFilename, String info, Boolean onlyAuxiliary, Boolean doNotNavigateAfterLoaded, PackageContainerBase takeOverContainer, String storeFnToLRU, Boolean indexItems) in D:\a\aasx-package-explorer\aasx-package-explorer\src\AasxPackageExplorer\MainWindow.xaml.cs:line 294
at AasxPackageExplorer.MainWindow.<CommandBinding_GeneralDispatch>d__5.MoveNext() in D:\a\aasx-package-explorer\aasx-package-explorer\src\AasxPackageExplorer\MainWindow.CommandBindings.cs:line 266
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by BirgitBoss** [comment]
There are different interpretation of how to handle path conformant to the AASX specification and which features are supported by which tools. See e.g. https://github.com/eclipse-esmf/esmf-sdk/issues/488

In the moment therefore please import the generated xml file.

**Comment by Punith-Arumilli** [comment]
I exported AAS as XML using SAMM CLI and imported it in AASX Package Explorer. There are no error during importing but all the properties are miss in the shell, like in my application (trainDistanceCovered, trackRadius, trainSpeed, trainGradient, slopeX, slopeY) are the properties, they are missing. 

<img width="907" alt="Screenshot 2024-01-15 091657" src="https://github.com/eclipse-esmf/esmf-sdk/assets/146142447/c0174e69-9694-4b42-8ee3-0c1693708811">

<img width="409" alt="Screenshot 2024-01-15 091824" src="https://github.com/eclipse-esmf/esmf-sdk/assets/146142447/bd501a5f-212e-4250-a95e-33b3433ac9cd">

[MeasurementUnit.pdf](https://github.com/eclipse-esmf/esmf-sdk/files/13936674/MeasurementUnit.pdf)

**Comment by Punith-Arumilli** [comment]
Yeah, by refering the already created submodel for the existing AAS the properties are visable, Thank you very much @BirgitBoss .
